%sql 

CREATE OR REPLACE TEMP VIEW vw_consumo_final AS 
WITH 
 VARS AS ( 
 SELECT 
 DATE(FROM_UTC_TIMESTAMP(current_timestamp(), 'America/Sao_Paulo')) AS HOJE_SP, 
 FROM_UTC_TIMESTAMP(current_timestamp(), 'America/Sao_Paulo') AS AGORA_SP_TS, 
 3 AS RN_LIMIT, 
 3 AS RN_LIMIT_REDIS_ANALYST, 
 1 AS EXCLUI_ANALISTAS_REDIS 
 ), 
 BASE_TMP AS ( 
 SELECT 
 A.*, 
 translate( UPPER(TRIM(A.DISTRIBUICAO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) AS DIST_NM_NORM, 
 UPPER(TRIM(A.DPROC_DS_PROCESSO)) AS GRUPO_PROC, 
 UPPER(TRIM(A.COMPLEMENTO)) AS GRUPO_COMPL, 
 COALESCE(A.DTULTATZ, A.DT_INICIO_ATIVIDADE) AS TS_REF 
 FROM dbw.sbx_bu_gestao_rede.workflow_gestao_de_rede_ouvidoria_nip A 
 ), 
 WA_MAX AS ( 
 SELECT 
 IDWORKFLOW, 
 MAX(DT_ATRIBUICAO) AS DT_ATRIBUICAO_MAX 
 FROM dbw.sbx_bu_gestao_rede.workflow_atribuicao_ouvidoria_nip 
 GROUP BY IDWORKFLOW 
 ), 
 SAIDA_21 AS ( 
 SELECT * 
 FROM ( 
 SELECT 
 B.DISTRIBUICAO, 
 B.CODIDENTIFICACAO, 
 B.NOMEIDENTIFICACAO, 
 CASE 
 WHEN UPPER(TRIM(B.FASE_DISTRIBUICAO)) = 'REDISTRIBUICAO' THEN '🔄 Redistribuição' 
 WHEN UPPER(TRIM(B.FASE_DISTRIBUICAO)) = 'RETORNO' THEN '↩️ Retorno' 
 WHEN UPPER(TRIM(B.FASE_DISTRIBUICAO)) = 'NOVO' THEN '🆕 Novo' 
 ELSE B.FASE_DISTRIBUICAO 
 END AS FASE, 
 B.DPROC_DS_PROCESSO, 
 B.COMPLEMENTO, 
 B.GRUPO_RESPONSAVEL, 
 B.IDWORKFLOW, 
 B.DT_INICIO_WORKFLOW, 
 B.DT_LIMITE_WORKFLOW, 
 B.HR_LIMITE_WORKFLOW, 
 B.DT_INICIO_ATIVIDADE, 
 B.HR_INICIO_ATIVIDADE, 
 B.DT_LIMITE_ATIVIDADE, 
 B.HR_LIMITE_ATIVIDADE, 
 CASE 
 WHEN W.DT_ATRIBUICAO_MAX IS NOT NULL THEN DATE_FORMAT(FROM_UTC_TIMESTAMP(W.DT_ATRIBUICAO_MAX, 'America/Sao_Paulo'), 'dd/MM/yyyy HH:mm:ss') 
 ELSE DATE_FORMAT(FROM_UTC_TIMESTAMP(B.TS_REF, 'America/Sao_Paulo'), 'dd/MM/yyyy HH:mm:ss') 
 END AS DATA_ROBO, 
 DATE_FORMAT(FROM_UTC_TIMESTAMP(B.TS_REF, 'America/Sao_Paulo'), 'dd/MM/yyyy HH:mm:ss') AS DATA_STATUS_ANALISTA, 
 translate( UPPER(TRIM(B.DISTRIBUICAO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) AS DIST_NM_NORM, 
 UPPER(TRIM(B.DPROC_DS_PROCESSO)) AS GRUPO_PROC, 
 UPPER(TRIM(B.COMPLEMENTO)) AS GRUPO_COMPL 
 FROM BASE_TMP B 
 LEFT JOIN WA_MAX W 
 ON W.IDWORKFLOW = B.IDWORKFLOW 
 ) X 
 -- [6] ORDER BY 1: evita sort desnecessário sobre a chave de partição
 QUALIFY ROW_NUMBER() OVER (PARTITION BY IDWORKFLOW ORDER BY 1) = 1 
 ), 
 DNA_MAX AS ( 
 SELECT MAX(DTCARGA) AS DTCARGA_MAX 
 FROM dbw.sbx_bu_gestao_rede.dna_ouvidoria_nip 
 ), 
 DNA_ATIVOS_TMP AS ( 
 SELECT 
 UPPER(TRIM(GRUPO)) AS GRUPO, 
 UPPER(TRIM(ANALISTA)) AS ANALISTA, 
 translate( UPPER(TRIM(ANALISTA)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) AS ANALISTA_NM, 
 UPPER(TRIM(STATUS)) AS STATUS, 
 DTCARGA 
 FROM dbw.sbx_bu_gestao_rede.dna_ouvidoria_nip 
 WHERE DTCARGA = (SELECT DTCARGA_MAX FROM DNA_MAX) 
 ), 
 DNA_STATUS_GRP AS ( 
 SELECT 
 GRUPO, 
 ANALISTA_NM, 
 FIRST_VALUE(STATUS) OVER ( 
 PARTITION BY ANALISTA_NM, GRUPO 
 ORDER BY CASE 
 WHEN STATUS = 'REDISTRIBUIR' THEN 3 
 WHEN STATUS = 'ATIVO' THEN 2 
 ELSE 1 
 END DESC, 
 ANALISTA ASC 
 ) AS STATUS_FINAL 
 FROM DNA_ATIVOS_TMP 
 ), 
 DNA_REDIS_BY_GRP AS ( 
 SELECT DISTINCT 
 GRUPO, 
 ANALISTA_NM 
 FROM DNA_STATUS_GRP 
 WHERE STATUS_FINAL = 'REDISTRIBUIR' 
 ), 
 WF_HIST AS ( 
 SELECT 
 A.IDWORKFLOW, 
 E.DAGWO_NM_AGENTE AS ANALISTA_HIST, 
 translate( UPPER(TRIM(E.DAGWO_NM_AGENTE)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) AS NM_NORM, 
 A.DTHRFIM, 
 ROW_NUMBER() OVER (PARTITION BY A.IDWORKFLOW ORDER BY A.DTHRFIM DESC) AS RN 
 FROM dbw.workflow_cur_view.wfworkflowatividade A 
 JOIN dbw.OPERADORA_dw_view.dagwo_agente_workflow E 
 ON A.IDAGENTE = E.DAGWO_CD_AGENTE 
 JOIN ( 
 SELECT DISTINCT ANALISTA_NM 
 FROM DNA_ATIVOS_TMP 
 ) D 
 ON D.ANALISTA_NM = translate( UPPER(TRIM(E.DAGWO_NM_AGENTE)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) 
 WHERE A.DESCRICAO <> 'ABERTURA' 
 AND E.DAGWO_NM_AGENTE <> 'NAO INFORMADO' 
 ), 
 WF_HIST_ANY AS ( 
 SELECT DISTINCT IDWORKFLOW 
 FROM WF_HIST 
 ), 
 WF_LAST_DTHR AS ( 
 SELECT 
 IDWORKFLOW, 
 DTHRFIM AS DTHRFIM_ULT 
 FROM WF_HIST 
 WHERE RN = 1 
 ), 
 WF_LAST_CLOSE_ALL AS ( 
 SELECT 
 IDWORKFLOW, 
 ANALISTA_HIST AS ANALISTA_ULTIMO_GERAL, 
 DTHRFIM AS ULTIMO_FECHAMENTO_GERAL 
 FROM ( 
 SELECT 
 H.IDWORKFLOW, 
 H.ANALISTA_HIST, 
 H.DTHRFIM, 
 ROW_NUMBER() OVER (PARTITION BY H.IDWORKFLOW ORDER BY H.DTHRFIM DESC) AS RN_ALL 
 FROM WF_HIST H 
 ) T 
 WHERE RN_ALL = 1 
 ), 
 WF_LAST_CLOSE_ALL_NORM AS ( 
 SELECT 
 IDWORKFLOW, 
 ANALISTA_ULTIMO_GERAL, 
 translate( UPPER(TRIM(ANALISTA_ULTIMO_GERAL)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) AS LCA_NM_NORM, 
 ULTIMO_FECHAMENTO_GERAL 
 FROM WF_LAST_CLOSE_ALL 
 ), 
 WF_LAST_N_BY_ULT_ANALISTA AS ( 
 SELECT 
 H.IDWORKFLOW, 
 H.DTHRFIM, 
 ROW_NUMBER() OVER (PARTITION BY H.IDWORKFLOW ORDER BY H.DTHRFIM DESC) AS RN_A 
 FROM WF_HIST H 
 JOIN WF_LAST_CLOSE_ALL LCA 
 ON LCA.IDWORKFLOW = H.IDWORKFLOW 
 AND UPPER(TRIM(H.ANALISTA_HIST)) = UPPER(TRIM(LCA.ANALISTA_ULTIMO_GERAL)) 
 ), 
 WF_LAST_N_BY_ULT_ANALISTA_TOP AS ( 
 SELECT 
 IDWORKFLOW, 
 DTHRFIM 
 FROM WF_LAST_N_BY_ULT_ANALISTA 
 WHERE RN_A <= (SELECT RN_LIMIT_REDIS_ANALYST FROM VARS) 
 ), 
 WF_LAST_N_FLAG AS ( 
 SELECT DISTINCT 
 IDWORKFLOW, 
 1 AS HAS_LASTN 
 FROM WF_LAST_N_BY_ULT_ANALISTA_TOP 
 ), 
 WF_LAST_CLOSE_BY_ANALYST AS ( 
 SELECT 
 IDWORKFLOW, 
 ANALISTA_HIST, 
 MAX(DTHRFIM) AS ULTIMO_FECHAMENTO_ANALISTA 
 FROM WF_HIST 
 GROUP BY IDWORKFLOW, ANALISTA_HIST 
 ), 
 LCB_DIST AS ( 
 SELECT 
 LCB.IDWORKFLOW, 
 LCB.ULTIMO_FECHAMENTO_ANALISTA AS ULT_FECHAMENTO_DIST 
 FROM WF_LAST_CLOSE_BY_ANALYST LCB 
 JOIN SAIDA_21 S 
 ON S.IDWORKFLOW = LCB.IDWORKFLOW 
 AND translate( UPPER(TRIM(LCB.ANALISTA_HIST)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) = translate( UPPER(TRIM(S.DISTRIBUICAO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC' ) 
 ), 
 LCB_DIST_FLAG AS ( 
 SELECT DISTINCT IDWORKFLOW 
 FROM LCB_DIST 
 WHERE ULT_FECHAMENTO_DIST IS NOT NULL 
 ), 
 LCB_ULTIMO AS ( 
 SELECT 
 LCB.IDWORKFLOW, 
 LCB.ULTIMO_FECHAMENTO_ANALISTA AS ULT_FECHAMENTO_ULT 
 FROM WF_LAST_CLOSE_BY_ANALYST LCB 
 JOIN WF_LAST_CLOSE_ALL LCA 
 ON LCA.IDWORKFLOW = LCB.IDWORKFLOW 
 AND UPPER(TRIM(LCB.ANALISTA_HIST)) = UPPER(TRIM(LCA.ANALISTA_ULTIMO_GERAL)) 
 ), 
 DNA_STATUS_ULT_GRP AS ( 
 SELECT 
 S.IDWORKFLOW, 
 G.STATUS_FINAL AS STATUS_ULT 
 FROM SAIDA_21 S 
 LEFT JOIN WF_LAST_CLOSE_ALL_NORM L 
 ON L.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN DNA_STATUS_GRP G 
 ON G.ANALISTA_NM = L.LCA_NM_NORM 
 AND G.GRUPO IN (S.GRUPO_PROC, S.GRUPO_COMPL) 
 ), 
 DNA_STATUS_CUR_GRP AS ( 
 SELECT 
 S.IDWORKFLOW, 
 G.STATUS_FINAL AS STATUS_CUR 
 FROM SAIDA_21 S 
 LEFT JOIN DNA_STATUS_GRP G 
 ON G.ANALISTA_NM = S.DIST_NM_NORM 
 AND G.GRUPO IN (S.GRUPO_PROC, S.GRUPO_COMPL) 
 ), 
 COMPART_JOIN AS ( 
 SELECT 
 S.IDWORKFLOW, 
 CASE 
 WHEN L.LCA_NM_NORM <> S.DIST_NM_NORM 
 AND DA_CUR.STATUS = 'ATIVO' 
 AND DA_HIST.STATUS = 'ATIVO' 
 AND DA_CUR.GRUPO = DA_HIST.GRUPO 
 AND (DA_CUR.GRUPO = S.GRUPO_PROC OR DA_CUR.GRUPO = S.GRUPO_COMPL) 
 THEN 1 
 ELSE 0 
 END AS IS_COMPART 
 FROM SAIDA_21 S 
 LEFT JOIN WF_LAST_CLOSE_ALL_NORM L 
 ON L.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN DNA_ATIVOS_TMP DA_CUR 
 ON DA_CUR.ANALISTA_NM = S.DIST_NM_NORM 
 AND (DA_CUR.GRUPO = S.GRUPO_PROC OR DA_CUR.GRUPO = S.GRUPO_COMPL) 
 LEFT JOIN DNA_ATIVOS_TMP DA_HIST 
 ON DA_HIST.ANALISTA_NM = L.LCA_NM_NORM 
 AND (DA_HIST.GRUPO = S.GRUPO_PROC OR DA_HIST.GRUPO = S.GRUPO_COMPL) 
 ), 
 SOBERANIA AS ( 
 SELECT 
 S.IDWORKFLOW, 
 CASE 
 WHEN U.STATUS_ULT = 'REDISTRIBUIR' AND LN.HAS_LASTN = 1 THEN 1 
 ELSE 0 
 END AS IS_REDIS, 
 C.IS_COMPART, 
 CASE 
 WHEN H.IDWORKFLOW IS NOT NULL AND DF.IDWORKFLOW IS NOT NULL THEN 1 
 ELSE 0 
 END AS IS_RETORNO 
 FROM SAIDA_21 S 
 LEFT JOIN DNA_STATUS_ULT_GRP U 
 ON U.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN WF_LAST_N_FLAG LN 
 ON LN.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN COMPART_JOIN C 
 ON C.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN WF_HIST_ANY H 
 ON H.IDWORKFLOW = S.IDWORKFLOW 
 LEFT JOIN LCB_DIST_FLAG DF 
 ON DF.IDWORKFLOW = S.IDWORKFLOW 
 ), 
 PRE_FINAL AS ( 
 SELECT 
 S.*, 
 SOB.IS_REDIS, 
 SOB.IS_COMPART, 
 SOB.IS_RETORNO, 
 CASE 
 WHEN SOB.IS_REDIS = 1 THEN '🔄 Redistribuição' 
 WHEN SOB.IS_COMPART = 1 THEN '⚠️ Demanda Compartilhada' 
 WHEN SOB.IS_RETORNO = 1 THEN '↩️ Retorno' 
 ELSE '🆕 Novo' 
 END AS FASE_FINAL 
 FROM SAIDA_21 S 
 LEFT JOIN SOBERANIA SOB 
 ON SOB.IDWORKFLOW = S.IDWORKFLOW 
 ), 
 SELECT_FINAL AS ( 
 SELECT 
 P.IDWORKFLOW, 
 P.DISTRIBUICAO, 
 P.CODIDENTIFICACAO, 
 P.NOMEIDENTIFICACAO, 
 P.DIST_NM_NORM, 
 P.FASE_FINAL AS FASE, 
 P.DPROC_DS_PROCESSO, 
 P.COMPLEMENTO, 
 P.GRUPO_RESPONSAVEL, 
 P.GRUPO_PROC, 
 P.GRUPO_COMPL, 
 P.DT_INICIO_WORKFLOW, 
 P.DT_LIMITE_WORKFLOW, 
 P.HR_LIMITE_WORKFLOW, 
 P.DT_INICIO_ATIVIDADE, 
 P.HR_INICIO_ATIVIDADE, 
 P.DT_LIMITE_ATIVIDADE, 
 P.HR_LIMITE_ATIVIDADE, 
 P.DATA_ROBO, 
 P.DATA_STATUS_ANALISTA, 
 'ATIVO' AS STATUS_ROBO_VISUALIZOU, 
 NULL AS BALANCEAMENTO_COMENTARIO_ROBO, 
 LCB_DIST.ULT_FECHAMENTO_DIST, 
 LCB_ULTIMO.ULT_FECHAMENTO_ULT, 
 LCA.ANALISTA_ULTIMO_GERAL, 
 WFL.DTHRFIM_ULT 
 FROM PRE_FINAL P 
 LEFT JOIN LCB_DIST 
 ON LCB_DIST.IDWORKFLOW = P.IDWORKFLOW 
 LEFT JOIN LCB_ULTIMO 
 ON LCB_ULTIMO.IDWORKFLOW = P.IDWORKFLOW 
 LEFT JOIN WF_LAST_CLOSE_ALL LCA 
 ON LCA.IDWORKFLOW = P.IDWORKFLOW 
 LEFT JOIN WF_LAST_DTHR WFL 
 ON WFL.IDWORKFLOW = P.IDWORKFLOW 
 ), 
 OBS_ABERTURA_RAW AS ( 
 SELECT 
 W.IDWORKFLOW, 
 W.TEXTO, 
 -- [6] ORDER BY 1: evita sort desnecessário sobre a chave de partição
 ROW_NUMBER() OVER (PARTITION BY W.IDWORKFLOW ORDER BY 1) AS RN 
 FROM dbw.workflow_cur_view.wfworkflow W 
 ), 
 OBS_ABERTURA AS ( 
 SELECT 
 IDWORKFLOW, 
 REGEXP_REPLACE( 
 TRIM( 
 REGEXP_REPLACE( 
 REGEXP_REPLACE( 
 REGEXP_REPLACE(COALESCE(TEXTO,''), '(?i)<[^&]*>', ' '), 
 '<[^>]*>', 
 ' ' 
 ), 
 '[^A-Za-zÀ-ÿ0-9\\s]', 
 ' ' 
 ) 
 ), 
 '\\s+', 
 ' ' 
 ) AS OBSFECHAMENTO 
 FROM OBS_ABERTURA_RAW 
 WHERE RN = 1 
 ), 
 -- [1] WFWPC_BASE: scan único substitui as 10 CTEs separadas
 --     (UF_NIP_NAOASSISTENCIAL, UF_OUVIDORIA, UF_CONSUMIDOR_GOV,
 --      UF_NIP_ASSISTENCIAL, UF_ORGAOS_REPRESENTACAO +
 --      5 MUNICIPIO_*) que faziam o mesmo JOIN 4x cada.
 --     Os joins a wfworkflow e wftpcomplemento também foram
 --     removidos — nenhuma coluna deles chegava ao SELECT final.
 WFWPC_BASE AS (
   SELECT i.IDWORKFLOW, i.IDCONTROLE, i.VALOR, i.IDPROCESSO
   FROM dbw.workflow_cur_view.wfworkflowprocessoxcontrole i
   JOIN dbw.workflow_cur_view.wfworkflowatividade a
     ON  i.IDWORKFLOW = a.IDWORKFLOW
     AND a.DESCRICAO  = 'ABERTURA'
   WHERE
       (i.IDPROCESSO = '7718'            AND i.IDCONTROLE IN ('255', '309'))
    OR (i.IDPROCESSO IN ('6298', '6299') AND i.IDCONTROLE IN ('165', '166'))
    OR (i.IDPROCESSO = '7501'            AND i.IDCONTROLE IN ('145', '146'))
    OR (i.IDPROCESSO = '7717'            AND i.IDCONTROLE IN ('27',  '28'))
    OR (i.IDPROCESSO = '7292'            AND i.IDCONTROLE IN ('2',   '3'))
 ),
 UF_CONSOLIDADA AS ( 
 SELECT X.IDWORKFLOW, 
 MAX(CASE WHEN X.IDPROCESSO = '7718'            AND X.IDCONTROLE = '255' THEN TRIM(X.VALOR) END) AS UF_NIP_NAOASSISTENCIAL, 
 MAX(CASE WHEN X.IDPROCESSO IN ('6298','6299')  AND X.IDCONTROLE = '165' THEN TRIM(X.VALOR) END) AS UF_OUVIDORIA, 
 MAX(CASE WHEN X.IDPROCESSO = '7501'            AND X.IDCONTROLE = '145' THEN TRIM(X.VALOR) END) AS UF_CONSUMIDOR_GOV, 
 MAX(CASE WHEN X.IDPROCESSO = '7717'            AND X.IDCONTROLE = '27'  THEN TRIM(X.VALOR) END) AS UF_NIP_ASSISTENCIAL, 
 MAX(CASE WHEN X.IDPROCESSO = '7292'            AND X.IDCONTROLE = '2'   THEN TRIM(X.VALOR) END) AS UF_ORGAOS_REPRESENTACAO 
 FROM WFWPC_BASE X
 GROUP BY X.IDWORKFLOW 
 ), 
 MUNICIPIO_CONSOLIDADO AS ( 
 SELECT X.IDWORKFLOW, 
 MAX(CASE WHEN X.IDPROCESSO = '7718'            AND X.IDCONTROLE = '309' THEN TRIM(X.VALOR) END) AS MUNICIPIO_NIP_NAOASSISTENCIAL, 
 MAX(CASE WHEN X.IDPROCESSO IN ('6298','6299')  AND X.IDCONTROLE = '166' THEN TRIM(X.VALOR) END) AS MUNICIPIO_OUVIDORIA, 
 MAX(CASE WHEN X.IDPROCESSO = '7501'            AND X.IDCONTROLE = '146' THEN TRIM(X.VALOR) END) AS MUNICIPIO_CONSUMIDOR_GOV, 
 MAX(CASE WHEN X.IDPROCESSO = '7717'            AND X.IDCONTROLE = '28'  THEN TRIM(X.VALOR) END) AS MUNICIPIO_NIP_ASSISTENCIAL, 
 MAX(CASE WHEN X.IDPROCESSO = '7292'            AND X.IDCONTROLE = '3'   THEN TRIM(X.VALOR) END) AS MUNICIPIO_ORGAOS_REPRESENTACAO 
 FROM WFWPC_BASE X
 GROUP BY X.IDWORKFLOW 
 ), 
 -- [2] OPERADORA360_base: scan único de fcrat_crm_atendimento
 --     substitui OPERADORA360_motivos_aggr (linha 473 original) e
 --     OPERADORA360_casos (linha 487 original) que liam a mesma
 --     tabela separadamente. OPERADORA360_motivos_fix eliminada
 --     (lógica de REGEXP_REPLACE incorporada aqui).
 OPERADORA360_base AS (
   SELECT
     FCRAT_CD_MARCA_OTICA,
     REGEXP_REPLACE(REGEXP_REPLACE(
       INITCAP(TRIM(FCRAT_NM_MOTIVO_AGENDAMENTO)),
       '\\bNip\\b', 'NIP'), '\\bGih\\b', 'GIH') AS MOTIVO_FMT,
     FCRAT_CD_SOLICITACAO,
     FCRAT_DT_FECHAMENTO,
     FCRAT_DT_MARCO_SLA_SAIDA
   FROM dbw.OPERADORA360_dw_view.fcrat_crm_atendimento
   WHERE FCRAT_CD_MARCA_OTICA IS NOT NULL
     AND FCRAT_NM_MOTIVO_AGENDAMENTO IS NOT NULL
 ),
 OPERADORA360_motivos_aggr AS ( 
 SELECT FCRAT_CD_MARCA_OTICA AS CD_MARCA_OTICA, MOTIVO_FMT, COUNT(DISTINCT FCRAT_CD_SOLICITACAO) AS QTD_CASOS 
 FROM OPERADORA360_base
 GROUP BY FCRAT_CD_MARCA_OTICA, MOTIVO_FMT
 ), 
 OPERADORA360_motivos_fmt AS ( 
 SELECT CD_MARCA_OTICA, CONCAT_WS(', ', TRANSFORM( ARRAY_SORT(COLLECT_LIST(NAMED_STRUCT('ord', -QTD_CASOS, 'mot', MOTIVO_FMT, 'txt', CONCAT(MOTIVO_FMT, ' x ', CAST(QTD_CASOS AS STRING))))), x -> x.txt )) AS MOTIVOS_360 
 FROM OPERADORA360_motivos_aggr 
 GROUP BY CD_MARCA_OTICA 
 ), 
 OPERADORA360_casos AS ( 
 SELECT FCRAT_CD_MARCA_OTICA AS CD_MARCA_OTICA, MOTIVO_FMT, 
 sort_array(collect_set(CONCAT( CASE WHEN FCRAT_DT_FECHAMENTO = '1900-01-01T00:00:00.000+00:00' AND FCRAT_DT_MARCO_SLA_SAIDA = '1900-01-01T00:00:00.000+00:00' THEN '*' ELSE '' END, CAST(FCRAT_CD_SOLICITACAO AS string) ))) AS IDS, 
 size(collect_set(FCRAT_CD_SOLICITACAO)) AS QTD_CASOS 
 FROM OPERADORA360_base
 GROUP BY FCRAT_CD_MARCA_OTICA, MOTIVO_FMT
 ), 
 OPERADORA360_casos_fmt AS ( 
 SELECT CD_MARCA_OTICA, CONCAT_WS(CONCAT(CHR(10), CHR(10)), TRANSFORM( ARRAY_SORT(COLLECT_LIST(NAMED_STRUCT('ord', -QTD_CASOS, 'mot', MOTIVO_FMT, 'txt', CONCAT(MOTIVO_FMT, ' - ', CONCAT_WS('; ', IDS))))), x -> x.txt )) AS OPERADORA360_LINHAS 
 FROM OPERADORA360_casos 
 GROUP BY CD_MARCA_OTICA 
 ), 
 wf_hist_aberto AS ( 
 SELECT CAST(d.IDWORKFLOW AS STRING) AS IDWORKFLOW, MAX(CASE WHEN substr(CAST(d.DTHRFIM AS STRING), 1, 10) = '1900-01-01' THEN 1 ELSE 0 END) AS IS_ABERTO 
 FROM dbw.workflow_cur_view.wfworkflow d 
 GROUP BY CAST(d.IDWORKFLOW AS STRING) 
 ), 
 wf_hist_src AS ( 
 SELECT d.CODIDENTIFICACAO, INITCAP(TRIM(c.DPROC_DS_PROCESSO)) AS PROCESSO_INIT, d.IDWORKFLOW, COALESCE(wa.IS_ABERTO, 0) AS IS_ABERTO 
 FROM dbw.workflow_cur_view.wfworkflow d 
 LEFT JOIN dbw.OPERADORA_dw_view.dproc_processo c ON d.IDPROCESSO = c.DPROC_CD_PROCESSO 
 LEFT JOIN wf_hist_aberto wa ON wa.IDWORKFLOW = CAST(d.IDWORKFLOW AS STRING) 
 WHERE TO_DATE(d.DTHRCANCELAMENTO) = '1900-01-01' 
 ), 
 wf_hist_src_fix AS ( 
 SELECT CODIDENTIFICACAO, REGEXP_REPLACE(REGEXP_REPLACE(PROCESSO_INIT, '\\bNip\\b', 'NIP'), '\\bGih\\b', 'GIH') AS PROCESSO_FMT, IDWORKFLOW, IS_ABERTO 
 FROM wf_hist_src 
 ), 
 keys_norm_ov AS ( 
 SELECT DISTINCT S.CODIDENTIFICACAO, CASE WHEN REGEXP_REPLACE(CAST(S.CODIDENTIFICACAO AS STRING), '^0+', '') = '' THEN '0' ELSE REGEXP_REPLACE(CAST(S.CODIDENTIFICACAO AS STRING), '^0+', '') END AS CRM_TRIM, LPAD(REGEXP_REPLACE(CAST(S.CODIDENTIFICACAO AS STRING), '^0+', ''), 9, '0') AS CRM_PAD9 
 FROM SAIDA_21 S WHERE S.CODIDENTIFICACAO IS NOT NULL 
 ), 
 keys_wf_ov AS ( 
 SELECT w.CODIDENTIFICACAO, CASE WHEN REGEXP_REPLACE(CAST(w.CODIDENTIFICACAO AS STRING), '^0+', '') = '' THEN '0' ELSE REGEXP_REPLACE(CAST(w.CODIDENTIFICACAO AS STRING), '^0+', '') END AS WF_TRIM, LPAD(REGEXP_REPLACE(CAST(w.CODIDENTIFICACAO AS STRING), '^0+', ''), 9, '0') AS WF_PAD9, w.PROCESSO_FMT, w.IDWORKFLOW, w.IS_ABERTO 
 FROM wf_hist_src_fix w 
 ), 
 -- [3] keys_joined: OR-JOIN resolvido via UNION
 --     O padrão ON (WF_TRIM = CRM_TRIM OR WF_PAD9 = CRM_PAD9)
 --     impedia hash join no Spark e aparecia duas vezes
 --     (wf_hist_aggr + wf_hist_ids). Ambas as CTEs consomem
 --     agora este ponto único com hash join habilitado.
 keys_joined AS (
   SELECT k.CRM_TRIM, k.CRM_PAD9, kw.PROCESSO_FMT, kw.IDWORKFLOW, kw.IS_ABERTO
   FROM keys_norm_ov k JOIN keys_wf_ov kw ON kw.WF_TRIM = k.CRM_TRIM
   UNION
   SELECT k.CRM_TRIM, k.CRM_PAD9, kw.PROCESSO_FMT, kw.IDWORKFLOW, kw.IS_ABERTO
   FROM keys_norm_ov k JOIN keys_wf_ov kw ON kw.WF_PAD9 = k.CRM_PAD9
 ),
 wf_hist_aggr AS ( 
 SELECT CRM_TRIM, CRM_PAD9, PROCESSO_FMT, COUNT(DISTINCT IDWORKFLOW) AS QTD 
 FROM keys_joined
 GROUP BY CRM_TRIM, CRM_PAD9, PROCESSO_FMT
 ), 
 wf_hist_fmt AS ( 
 SELECT CRM_TRIM, CRM_PAD9, CONCAT_WS(', ', TRANSFORM( ARRAY_SORT(COLLECT_LIST(NAMED_STRUCT('ord', -QTD, 'proc', PROCESSO_FMT, 'txt', CONCAT(PROCESSO_FMT, ' x ', CAST(QTD AS STRING))))), x -> x.txt )) AS WF_360 
 FROM wf_hist_aggr 
 GROUP BY CRM_TRIM, CRM_PAD9 
 ), 
 wf_hist_ids AS ( 
 SELECT CRM_TRIM, CRM_PAD9, PROCESSO_FMT,
   sort_array(collect_set(CASE WHEN IS_ABERTO = 1 THEN CONCAT('*', CAST(IDWORKFLOW AS string)) ELSE CAST(IDWORKFLOW AS string) END)) AS IDS,
   size(collect_set(IDWORKFLOW)) AS QTD
 FROM keys_joined
 GROUP BY CRM_TRIM, CRM_PAD9, PROCESSO_FMT
 ), 
 wf_hist_ids_fmt AS ( 
 SELECT CRM_TRIM, CRM_PAD9, CONCAT_WS(CHR(10), TRANSFORM( ARRAY_SORT(COLLECT_LIST(NAMED_STRUCT('ord', -QTD, 'proc', PROCESSO_FMT, 'txt', CONCAT(PROCESSO_FMT, ' - ', CONCAT_WS('; ', IDS))))), x -> x.txt )) AS WF_LINHAS 
 FROM wf_hist_ids 
 GROUP BY CRM_TRIM, CRM_PAD9 
 ), 
 FINAL_BASE AS ( 
 SELECT 
 F.DISTRIBUICAO, F.CODIDENTIFICACAO, F.NOMEIDENTIFICACAO, F.FASE, F.DPROC_DS_PROCESSO, F.COMPLEMENTO, F.GRUPO_RESPONSAVEL, F.IDWORKFLOW, 
 CASE WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%NIP%NAO ASSISTENCIAL%' THEN COALESCE(UF.UF_NIP_NAOASSISTENCIAL, 'UF INESPECIFICA') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%OUVIDORIA%CLIENTE%' THEN COALESCE(UF.UF_OUVIDORIA, 'UF INESPECIFICA') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%OUVIDORIA%OUTROS%' THEN COALESCE(UF.UF_OUVIDORIA, 'UF INESPECIFICA') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%CONSUMIDOR%.GOV%' THEN COALESCE(UF.UF_CONSUMIDOR_GOV, 'UF INESPECIFICA') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%NIP%ASSISTENCIAL%' THEN COALESCE(UF.UF_NIP_ASSISTENCIAL, 'UF INESPECIFICA') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%ORGAOS%REPRESENTACAO%' THEN COALESCE(UF.UF_ORGAOS_REPRESENTACAO, 'UF INESPECIFICA') 
 ELSE 'UF inespecífica' END AS UF, 
 CASE WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%NIP%NAO ASSISTENCIAL%' THEN COALESCE(MUN.MUNICIPIO_NIP_NAOASSISTENCIAL, 'MUNICIPIO INESPECIFICO') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%OUVIDORIA%CLIENTE%' THEN COALESCE(MUN.MUNICIPIO_OUVIDORIA, 'MUNICIPIO INESPECIFICO') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%OUVIDORIA%OUTROS%' THEN COALESCE(MUN.MUNICIPIO_OUVIDORIA, 'MUNICIPIO INESPECIFICO') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%CONSUMIDOR%.GOV%' THEN COALESCE(MUN.MUNICIPIO_CONSUMIDOR_GOV, 'MUNICIPIO INESPECIFICO') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%NIP%ASSISTENCIAL%' THEN COALESCE(MUN.MUNICIPIO_NIP_ASSISTENCIAL, 'MUNICIPIO INESPECIFICO') 
 WHEN translate(UPPER(TRIM(F.DPROC_DS_PROCESSO)), 'ÁÀÃÂÉÈÊÍÌÎÓÒÕÔÚÙÛÇ', 'AAAAEEEIIIOOOOUUUC') LIKE '%ORGAOS%REPRESENTACAO%' THEN COALESCE(MUN.MUNICIPIO_ORGAOS_REPRESENTACAO, 'MUNICIPIO INESPECIFICO') 
 ELSE 'MUNICIPIO INESPECIFICO' END AS MUNICIPIO, 
 F.DT_INICIO_WORKFLOW, F.DT_LIMITE_WORKFLOW, F.HR_LIMITE_WORKFLOW, F.DT_INICIO_ATIVIDADE, F.HR_INICIO_ATIVIDADE, F.DT_LIMITE_ATIVIDADE, F.HR_LIMITE_ATIVIDADE, F.DATA_ROBO, F.DATA_STATUS_ANALISTA, 'ATIVO' AS STATUS_ROBO_VISUALIZOU, NULL AS BALANCEAMENTO_COMENTARIO_ROBO, 
 CASE WHEN CURRENT_DATE() > F.DT_LIMITE_ATIVIDADE THEN 'VENCIDO' WHEN CURRENT_DATE() = F.DT_LIMITE_ATIVIDADE THEN 'VENCENDO HOJE' WHEN CURRENT_DATE() < F.DT_LIMITE_ATIVIDADE THEN 'NO PRAZO' ELSE NULL END AS SLA_ATIVIDADE, 
 CASE WHEN UPPER(TRIM(REGEXP_REPLACE(F.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%REDISTRIBUIÇÃO%' THEN F.ANALISTA_ULTIMO_GERAL ELSE NULL END AS ANALISTA_SENDO_SUBSTITUIDO, 
 CONCAT_WS(CONCAT(CHR(10), CHR(10)), CASE WHEN UPPER(TRIM(REGEXP_REPLACE(F.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%COMPARTILHADA%' THEN CONCAT('🤖 O analista ', F.ANALISTA_ULTIMO_GERAL, ' fechou pela última vez em ', CASE WHEN F.ULT_FECHAMENTO_ULT IS NOT NULL THEN DATE_FORMAT(F.ULT_FECHAMENTO_ULT, 'dd/MM/yyyy HH:mm') ELSE 'DATA/HORA NÃO ENCONTRADAS' END, '. Se organize com colega para definir quem dará continuidade na demanda. Lembrando que a recomendação é de seguir a fidelização de casos, salvo exceções de cobertura.') 
 WHEN UPPER(TRIM(REGEXP_REPLACE(F.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%REDISTRIBUIÇÃO%' THEN CONCAT('🤖 ', 'Atividade finalizada pela última vez pelo analista substituído ', COALESCE(F.ANALISTA_ULTIMO_GERAL, 'ANALISTA NÃO IDENTIFICADO'), ' em ', CASE WHEN F.ULT_FECHAMENTO_ULT IS NOT NULL AND F.ULT_FECHAMENTO_DIST IS NULL THEN DATE_FORMAT(F.ULT_FECHAMENTO_ULT, 'dd/MM/yyyy HH:mm') WHEN F.ULT_FECHAMENTO_DIST IS NOT NULL THEN DATE_FORMAT(F.ULT_FECHAMENTO_DIST, 'dd/MM/yyyy HH:mm') ELSE 'DATA/HORA NÃO ENCONTRADAS' END ) 
 WHEN UPPER(TRIM(REGEXP_REPLACE(F.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%RETORNO%' THEN CONCAT('🤖 ', 'Atividade finalizada pela última vez pelo analista em ', CASE WHEN F.ULT_FECHAMENTO_DIST IS NOT NULL THEN DATE_FORMAT(F.ULT_FECHAMENTO_DIST, 'dd/MM/yyyy HH:mm') WHEN F.ULT_FECHAMENTO_ULT IS NOT NULL THEN DATE_FORMAT(F.ULT_FECHAMENTO_ULT, 'dd/MM/yyyy HH:mm') ELSE 'DATA/HORA NÃO ENCONTRADAS' END ) 
 ELSE NULL END, 
 CONCAT('OPERADORA360 :', CASE WHEN MC.OPERADORA360_LINHAS IS NOT NULL THEN CONCAT(CHR(10), MC.OPERADORA360_LINHAS) ELSE '' END), 
 CASE WHEN WF2.WF_LINHAS IS NOT NULL THEN CONCAT(CHR(10), CHR(10), CHR(10), 'WORKFLOW:', CHR(10), WF2.WF_LINHAS) END 
 ) AS REVISAO_COMENTARIO_ROBO_ORIG 
 FROM SELECT_FINAL F 
 LEFT JOIN UF_CONSOLIDADA UF ON UF.IDWORKFLOW = F.IDWORKFLOW 
 LEFT JOIN MUNICIPIO_CONSOLIDADO MUN ON MUN.IDWORKFLOW = F.IDWORKFLOW 
 LEFT JOIN OPERADORA360_motivos_fmt AM ON AM.CD_MARCA_OTICA = F.CODIDENTIFICACAO 
 LEFT JOIN OPERADORA360_casos_fmt MC ON MC.CD_MARCA_OTICA = F.CODIDENTIFICACAO 
 LEFT JOIN wf_hist_fmt WF_FMT ON WF_FMT.CRM_TRIM = CASE WHEN REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', '') = '' THEN '0' ELSE REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', '') END AND WF_FMT.CRM_PAD9 = LPAD(REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', ''), 9, '0') 
 LEFT JOIN wf_hist_ids_fmt WF2 ON WF2.CRM_TRIM = CASE WHEN REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', '') = '' THEN '0' ELSE REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', '') END AND WF2.CRM_PAD9 = LPAD(REGEXP_REPLACE(CAST(F.CODIDENTIFICACAO AS STRING), '^0+', ''), 9, '0') 
 LEFT JOIN DNA_REDIS_BY_GRP DRG ON DRG.ANALISTA_NM = F.DIST_NM_NORM AND DRG.GRUPO IN (F.GRUPO_PROC, F.GRUPO_COMPL) 
 WHERE (SELECT EXCLUI_ANALISTAS_REDIS FROM VARS) = 0 OR DRG.ANALISTA_NM IS NULL 
 ), 
 FINAL_AJUSTE AS ( 
 SELECT 
 fb.IDWORKFLOW, fb.DISTRIBUICAO, fb.CODIDENTIFICACAO, fb.NOMEIDENTIFICACAO, fb.FASE, fb.DPROC_DS_PROCESSO, fb.COMPLEMENTO, fb.GRUPO_RESPONSAVEL, fb.UF, fb.MUNICIPIO, fb.DT_INICIO_WORKFLOW, fb.DT_LIMITE_WORKFLOW, fb.HR_LIMITE_WORKFLOW, fb.DT_INICIO_ATIVIDADE, fb.HR_INICIO_ATIVIDADE, fb.DT_LIMITE_ATIVIDADE, fb.HR_LIMITE_ATIVIDADE, fb.DATA_ROBO, fb.DATA_STATUS_ANALISTA, fb.STATUS_ROBO_VISUALIZOU, fb.BALANCEAMENTO_COMENTARIO_ROBO, 
 CASE WHEN fb.DT_LIMITE_WORKFLOW IS NULL THEN NULL WHEN TO_TIMESTAMP(CONCAT(DATE_FORMAT(fb.DT_LIMITE_WORKFLOW,'yyyy-MM-dd'),' ',TRIM(fb.HR_LIMITE_WORKFLOW)),'yyyy-MM-dd HH:mm') < (SELECT AGORA_SP_TS FROM VARS) THEN 'VENCIDO' WHEN DATE(fb.DT_LIMITE_WORKFLOW) = (SELECT HOJE_SP FROM VARS) THEN 'VENCENDO HOJE' WHEN DATE(fb.DT_LIMITE_WORKFLOW) = DATE_ADD((SELECT HOJE_SP FROM VARS),1) THEN 'VENCENDO AMANHA' WHEN DATE(fb.DT_LIMITE_WORKFLOW) > DATE_ADD((SELECT HOJE_SP FROM VARS),1) THEN 'NO PRAZO' ELSE NULL END AS SLA_WORKFLOW, 
 CASE WHEN fb.DT_LIMITE_ATIVIDADE IS NULL THEN NULL WHEN TO_TIMESTAMP(CONCAT(DATE_FORMAT(fb.DT_LIMITE_ATIVIDADE,'yyyy-MM-dd'),' ',TRIM(fb.HR_LIMITE_ATIVIDADE)),'yyyy-MM-dd HH:mm') < (SELECT AGORA_SP_TS FROM VARS) THEN 'VENCIDO' WHEN DATE(fb.DT_LIMITE_ATIVIDADE) = (SELECT HOJE_SP FROM VARS) THEN 'VENCENDO HOJE' WHEN DATE(fb.DT_LIMITE_ATIVIDADE) = DATE_ADD((SELECT HOJE_SP FROM VARS),1) THEN 'VENCENDO AMANHA' WHEN DATE(fb.DT_LIMITE_ATIVIDADE) > DATE_ADD((SELECT HOJE_SP FROM VARS),1) THEN 'NO PRAZO' ELSE NULL END AS SLA_ATIVIDADE, 
 fb.ANALISTA_SENDO_SUBSTITUIDO, 
 CASE WHEN UPPER(TRIM(REGEXP_REPLACE(fb.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%RETORNO%' AND fb.REVISAO_COMENTARIO_ROBO_ORIG LIKE '%01/01/1900 00:00%' 
 THEN CONCAT('🤖 Atividade assumida pelo analista em ', DATE_FORMAT(fb.DT_INICIO_ATIVIDADE, 'dd/MM/yyyy'), CASE WHEN fb.REVISAO_COMENTARIO_ROBO_ORIG RLIKE '(?s)\\n\\n.+' THEN CONCAT(CHR(10), CHR(10), REGEXP_EXTRACT(fb.REVISAO_COMENTARIO_ROBO_ORIG, '(?s)^.*?\\n\\n(.*)$', 1)) ELSE '' END) 
 ELSE fb.REVISAO_COMENTARIO_ROBO_ORIG END AS REVISAO_COMENTARIO_ROBO 
 FROM FINAL_BASE fb 
 ), 
 FINAL_AJUSTE_COMPARTILHADA AS ( 
 SELECT 
 fa.IDWORKFLOW, fa.DISTRIBUICAO, fa.CODIDENTIFICACAO, fa.NOMEIDENTIFICACAO, fa.FASE, fa.DPROC_DS_PROCESSO, fa.COMPLEMENTO, fa.GRUPO_RESPONSAVEL, fa.UF, fa.MUNICIPIO, fa.DT_INICIO_WORKFLOW, fa.DT_LIMITE_WORKFLOW, fa.HR_LIMITE_WORKFLOW, fa.DT_INICIO_ATIVIDADE, fa.HR_INICIO_ATIVIDADE, fa.DT_LIMITE_ATIVIDADE, fa.HR_LIMITE_ATIVIDADE, fa.DATA_ROBO, fa.DATA_STATUS_ANALISTA, fa.STATUS_ROBO_VISUALIZOU, fa.BALANCEAMENTO_COMENTARIO_ROBO, fa.SLA_WORKFLOW, fa.SLA_ATIVIDADE, fa.ANALISTA_SENDO_SUBSTITUIDO, 
 CASE WHEN UPPER(TRIM(REGEXP_REPLACE(fa.FASE, '[^A-Za-zÀ-ÿ ]', ''))) LIKE '%COMPARTILHADA%' AND fa.REVISAO_COMENTARIO_ROBO LIKE '%01/01/1900%' 
 THEN CONCAT('🤖 O analista ', COALESCE(NULLIF(REGEXP_EXTRACT(fa.REVISAO_COMENTARIO_ROBO, '🤖 O analista (.*?) fechou', 1), ''), 'NÃO IDENTIFICADO'), ' assumiu sua demanda.Se organize com colega para definir quem dará continuidade na demanda. Lembrando que a recomendação é de seguir a fidelização de casos, salvo exceções de cobertura.', CASE WHEN fa.REVISAO_COMENTARIO_ROBO RLIKE '(?s)\\n\\n.+' THEN CONCAT(CHR(10), CHR(10), REGEXP_EXTRACT(fa.REVISAO_COMENTARIO_ROBO, '(?s)^.*?\\n\\n(.*)$', 1)) ELSE '' END) 
 ELSE fa.REVISAO_COMENTARIO_ROBO END AS REVISAO_COMENTARIO_ROBO 
 FROM FINAL_AJUSTE fa 
 ), 
 WF_ATUALIZACAO AS (
 SELECT IDWORKFLOW, MAX(DtUltAtz) AS DT_ATUALIZACAO
 FROM dbw.workflow_cur_view.wfworkflowatividade
 GROUP BY IDWORKFLOW
 ),
 FINAL_SELECT_AJUSTE AS ( 
 SELECT 
 A.IDWORKFLOW, 
 -- [4] CASE com AND 1=0 removido (dead code — condição sempre falsa)
 A.DISTRIBUICAO,
 A.CODIDENTIFICACAO, A.NOMEIDENTIFICACAO, C.DPLAN_NM_PRODUTO AS PLANO, 
 CASE WHEN UPPER(COALESCE(C.DPLAN_NM_PRODUTO, '')) RLIKE '(^\n\\W)(BLACK\nONE)(\\W\n$)' THEN '⚫ BLACK/ONE - PLANO PREMIUM ' WHEN UPPER(COALESCE(A.REVISAO_COMENTARIO_ROBO, '')) RLIKE 'JUDICIAL' THEN '🔴 URGENTE - JUDICIALIZADO' WHEN SIZE(FILTER(SPLIT(COALESCE(A.REVISAO_COMENTARIO_ROBO, ''), '\\n'), x -> UPPER(TRIM(REGEXP_EXTRACT(REGEXP_REPLACE(x, '^[^A-Za-zÀ-ÿ]*', ''), '^[^\\s:;,-]+', 0))) = UPPER(TRIM(REGEXP_EXTRACT(A.DPROC_DS_PROCESSO, '^[^\\s]+', 0))))) > 1 THEN '🟡 CRÍTICO - REINCIDENTE' ELSE NULL END AS `PERFIL_CRITICO_BENEFICIÁRIO`, 
 -- [4] CASE com AND 1=0 removido (dead code — condição sempre falsa)
 A.FASE,
 A.DPROC_DS_PROCESSO AS PROCESSO, A.COMPLEMENTO, A.GRUPO_RESPONSAVEL, A.IDWORKFLOW, A.UF, A.MUNICIPIO, A.DT_INICIO_WORKFLOW, A.DT_LIMITE_WORKFLOW, A.HR_LIMITE_WORKFLOW, A.DT_INICIO_ATIVIDADE, A.HR_INICIO_ATIVIDADE, A.DT_LIMITE_ATIVIDADE, A.HR_LIMITE_ATIVIDADE, A.DATA_ROBO, A.DATA_STATUS_ANALISTA, A.STATUS_ROBO_VISUALIZOU, A.SLA_WORKFLOW, A.SLA_ATIVIDADE, A.ANALISTA_SENDO_SUBSTITUIDO, 
 -- [4] CASE com AND 1=0 removido (dead code — condição sempre falsa)
 A.REVISAO_COMENTARIO_ROBO,
 OA.OBSFECHAMENTO AS OBSFECHAMENTO 
 FROM FINAL_AJUSTE_COMPARTILHADA A 
 LEFT JOIN dbw.OPERADORA_dw_view.dbene_beneficiario AS B ON A.CODIDENTIFICACAO = B.DBENE_NR_MARCA_OTICA 
 LEFT JOIN dbw.OPERADORA_dw_view.dplan_plano AS C ON B.DBENE_CD_PLANO = C.DPLAN_CD_PLANO 
 LEFT JOIN OBS_ABERTURA OA ON OA.IDWORKFLOW = A.IDWORKFLOW 
 -- [6] ORDER BY 1: evita sort desnecessário sobre a chave de partição
 QUALIFY ROW_NUMBER() OVER (PARTITION BY A.IDWORKFLOW ORDER BY 1) = 1 
 ), 
 CTE_VENCEU_COM_GESTAO_DE_REDE AS ( 
 SELECT DISTINCT 
 A.IDWORKFLOW, 
 F.DSCGRUPO AS GRUPO_RESPONSAVEL, 
 to_date(D.DTLIMITE) AS DT_LIMITE_WORKFLOW, 
 date_format(D.DTLIMITE, 'HH:mm') AS HR_LIMITE, 
 to_date(A.DTHRFIM) AS DT_FIM_ATIVIDADE, 
 date_format(A.DTHRFIM, 'HH:mm') AS HR_FIM, 
 CASE WHEN GRUPO_RESPONSAVEL LIKE "%GESTÃO DE REDE NACIONAL%" AND to_date(A.DTHRFIM) > DT_LIMITE_WORKFLOW THEN 'SIM - GESTAO DE REDE NACIONAL' 
 WHEN GRUPO_RESPONSAVEL LIKE "%GESTÃO DE REDE NACIONAL%" AND to_date(A.DTHRFIM) = DT_LIMITE_WORKFLOW AND HR_FIM > HR_LIMITE THEN 'SIM - GESTAO DE REDE NACIONAL' 
 WHEN GRUPO_RESPONSAVEL NOT LIKE "%GESTÃO DE REDE NACIONAL%" AND to_date(A.DTHRFIM) > DT_LIMITE_WORKFLOW THEN 'NÃO - ' || GRUPO_RESPONSAVEL 
 WHEN GRUPO_RESPONSAVEL NOT LIKE "%GESTÃO DE REDE NACIONAL%" AND to_date(A.DTHRFIM) = DT_LIMITE_WORKFLOW AND HR_FIM > HR_LIMITE THEN 'NÃO - ' || GRUPO_RESPONSAVEL 
 ELSE "" END VENCEU_COM_REDE_NACIONAL 
 FROM dbw.workflow_cur_view.wfworkflowatividade AS a 
 LEFT JOIN dbw.workflow_cur_view.wfprocessoatividade AS b ON a.IDATIVIDADE = b.IDATIVIDADE 
 LEFT JOIN dbw.OPERADORA_dw_view.dproc_processo AS c ON b.IDPROCESSO = c.DPROC_CD_PROCESSO 
 LEFT JOIN dbw.workflow_cur_view.wfworkflow AS d ON a.IDWORKFLOW = d.IDWORKFLOW 
 -- [5] LEFT JOIN dagwo_agente_workflow (e) removido — nenhuma coluna usada no SELECT
 -- [5] LEFT JOIN dtpci_tipo_complemento_item (g) removido — nenhuma coluna usada no SELECT
 LEFT JOIN dbw.workflow_cur_view.wfgrupo AS f ON B.IDGRUPOREALIZADOR = F.IDGRUPO 
 WHERE TO_DATE(A.DTHRFIM) <> '1900-01-01' 
 AND TO_DATE(D.DTHRINICIO) > '2024-12-31' 
 AND TO_DATE(D.DTHRCANCELAMENTO) = '1900-01-01' AND D.DTLIMITE < CURRENT_DATE AND (C.DPROC_DS_PROCESSO LIKE '%OUVIDORIA%' OR C.DPROC_DS_PROCESSO LIKE '%NIP%') 
 AND to_date(A.DTHRFIM) > to_date(D.DTLIMITE) 
 QUALIFY ROW_NUMBER() OVER ( 
 PARTITION BY A.IDWORKFLOW 
 ORDER BY DT_FIM_ATIVIDADE ASC, HR_FIM, A.IDWORKFLOW) = 1 
 ), 
 FERIADOS_NACIONAIS AS ( 
 SELECT EXPLODE(ARRAY( 
 -- 2024 
 DATE('2024-01-01'), DATE('2024-02-12'), DATE('2024-02-13'), 
 DATE('2024-03-29'), DATE('2024-04-21'), DATE('2024-05-01'), 
 DATE('2024-05-30'), DATE('2024-09-07'), DATE('2024-10-12'), 
 DATE('2024-11-02'), DATE('2024-11-15'), DATE('2024-11-20'), 
 DATE('2024-12-25'), 
 -- 2025 
 DATE('2025-01-01'), DATE('2025-03-03'), DATE('2025-03-04'), 
 DATE('2025-04-18'), DATE('2025-04-21'), DATE('2025-05-01'), 
 DATE('2025-06-19'), DATE('2025-09-07'), DATE('2025-10-12'), 
 DATE('2025-11-02'), DATE('2025-11-15'), DATE('2025-11-20'), 
 DATE('2025-12-25'), 
 -- 2026 
 DATE('2026-01-01'), DATE('2026-02-16'), DATE('2026-02-17'), 
 DATE('2026-04-03'), DATE('2026-04-21'), DATE('2026-05-01'), 
 DATE('2026-06-04'), DATE('2026-09-07'), DATE('2026-10-12'), 
 DATE('2026-11-02'), DATE('2026-11-15'), DATE('2026-11-20'), 
 DATE('2026-12-25'), 
 -- 2027 
 DATE('2027-01-01'), DATE('2027-02-15'), DATE('2027-02-16'), 
 DATE('2027-04-02'), DATE('2027-04-21'), DATE('2027-05-01'), 
 DATE('2027-05-27'), DATE('2027-09-07'), DATE('2027-10-12'), 
 DATE('2027-11-02'), DATE('2027-11-15'), DATE('2027-11-20'), 
 DATE('2027-12-25') 
 )) AS feriado 
 ), 
 DIAS_UTEIS_SEQ AS ( 
 SELECT t.dia 
 FROM (SELECT EXPLODE(SEQUENCE(DATE('2024-01-01'), DATE('2030-12-31'))) AS dia) t 
 LEFT JOIN FERIADOS_NACIONAIS f ON f.feriado = t.dia 
 WHERE DAYOFWEEK(t.dia) NOT IN (1, 7) 
 AND f.feriado IS NULL 
 ), 
 -- [7] DT_ATUALIZACAO absorvida aqui via JOIN com WF_ATUALIZACAO
 --     Remove o segundo LEFT JOIN WF_ATUALIZACAO do SELECT final
 DIAS_UTEIS_POR_WF AS ( 
 SELECT F.IDWORKFLOW, WUA.DT_ATUALIZACAO, COUNT(*) AS DIAS_UTEIS_DECORRIDOS 
 FROM FINAL_SELECT_AJUSTE F 
 LEFT JOIN WF_ATUALIZACAO WUA ON WUA.IDWORKFLOW = F.IDWORKFLOW 
 JOIN DIAS_UTEIS_SEQ D 
 ON D.dia >= DATE(F.DT_INICIO_WORKFLOW) 
 AND D.dia < (SELECT HOJE_SP FROM VARS) 
 GROUP BY F.IDWORKFLOW, WUA.DT_ATUALIZACAO
 ) 

 SELECT 
 F.DISTRIBUICAO, F.CODIDENTIFICACAO, F.NOMEIDENTIFICACAO, F.PLANO, F.`PERFIL_CRITICO_BENEFICIÁRIO`, F.FASE, F.PROCESSO, F.COMPLEMENTO, F.GRUPO_RESPONSAVEL, F.IDWORKFLOW, F.UF, F.MUNICIPIO, F.DT_INICIO_WORKFLOW, F.DT_LIMITE_WORKFLOW, F.HR_LIMITE_WORKFLOW, F.DT_INICIO_ATIVIDADE, F.HR_INICIO_ATIVIDADE, F.DT_LIMITE_ATIVIDADE, F.HR_LIMITE_ATIVIDADE, F.DATA_ROBO, F.DATA_STATUS_ANALISTA, DU.DT_ATUALIZACAO AS DT_ATUALIZACAO, F.STATUS_ROBO_VISUALIZOU, F.SLA_WORKFLOW, F.SLA_ATIVIDADE, F.ANALISTA_SENDO_SUBSTITUIDO, F.REVISAO_COMENTARIO_ROBO, F.OBSFECHAMENTO AS OBS, 
 CASE WHEN V.VENCEU_COM_REDE_NACIONAL = "" AND F.SLA_WORKFLOW ='VENCIDO' THEN 'SIM - GESTÃO DE REDE NACIONAL' WHEN V.VENCEU_COM_REDE_NACIOnal is NULL AND F.SLA_WORKFLOW ='VENCIDO' THEN 'SIM - GESTÃO DE REDE NACIONAL' ELSE V.VENCEU_COM_REDE_NACIONAL END AS VENCEU_COM_REDE_NACIONAL, 
 DU.DIAS_UTEIS_DECORRIDOS, 
 CASE WHEN DU.DIAS_UTEIS_DECORRIDOS > 5 THEN 'BACKLOG' ELSE 'NO PRAZO' END AS BACKLOG 

FROM FINAL_SELECT_AJUSTE F
-- [7] LEFT JOIN WF_ATUALIZACAO removido — DT_ATUALIZACAO vem de DIAS_UTEIS_POR_WF
LEFT JOIN CTE_VENCEU_COM_GESTAO_DE_REDE V
  ON F.IDWORKFLOW = V.IDWORKFLOW
LEFT JOIN DIAS_UTEIS_POR_WF DU
  ON DU.IDWORKFLOW = F.IDWORKFLOW;

 MERGE INTO dbw.sbx_bu_gestao_rede.workflow_atribuicao_ouvidoria_nip AS T 
 USING ( 
 SELECT IDWORKFLOW, `PERFIL_CRITICO_BENEFICIÁRIO` FROM vw_consumo_final 
 ) AS S 
 ON T.IDWORKFLOW = S.IDWORKFLOW 
 WHEN MATCHED THEN UPDATE SET T.`PERFIL_CRITICO_BENEFICIÁRIO` = S.`PERFIL_CRITICO_BENEFICIÁRIO`; 

CREATE OR REPLACE TABLE dbw.sbx_bu_gestao_rede.tb_classificacao_beneficiario_norteamento_ouvidoria_nip AS 
SELECT * FROM vw_consumo_final;

-- [8] OPTIMIZE: compacta arquivos Delta do destino para
--     reduzir fragmentação e acelerar leituras subsequentes
OPTIMIZE dbw.sbx_bu_gestao_rede.tb_classificacao_beneficiario_norteamento_ouvidoria_nip;
